[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault = "4AdBPP21dhJ2dbo8q4UkPn9LFLMLMNDHpURfJEiigLKj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/vivek/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
